import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import Chuck from "./chuck/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jokes etc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Chuck />
        {children}
        </body>
    </html>
  );
}